<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="6" failed="0" ignored="0" total="12" passed="6">
  <reporter-output>
    <line>
      <![CDATA[RunCount=1]]>
    </line>
    <line>
      <![CDATA[RunCount=2]]>
    </line>
    <line>
      <![CDATA[RunCount=3]]>
    </line>
    <line>
      <![CDATA[RunCount=1]]>
    </line>
    <line>
      <![CDATA[RunCount=2]]>
    </line>
    <line>
      <![CDATA[RunCount=3]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="154517" started-at="2019-07-12T05:30:05Z" finished-at="2019-07-12T05:32:39Z">
    <groups>
    </groups>
    <test name="Test2" duration-ms="154517" started-at="2019-07-12T05:30:05Z" finished-at="2019-07-12T05:32:39Z">
      <class name="com.f.dianqingoa.testcase.SuiteTest002_Logout">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.f.dianqingoa.testcase.SuiteTest002_Logout@1fc2b765]" name="beforeClass" is-config="true" duration-ms="24775" started-at="2019-07-12T05:30:27Z" finished-at="2019-07-12T05:30:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="testLogout()[pri:0, instance:com.f.dianqingoa.testcase.SuiteTest002_Logout@1fc2b765]" name="testLogout" duration-ms="2849" started-at="2019-07-12T05:30:52Z" finished-at="2019-07-12T05:30:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogout -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:com.f.dianqingoa.testcase.SuiteTest002_Logout@1fc2b765]" name="afterClass" is-config="true" duration-ms="3288" started-at="2019-07-12T05:30:55Z" finished-at="2019-07-12T05:30:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- com.f.dianqingoa.testcase.SuiteTest002_Logout -->
      <class name="com.f.dianqingoa.testcase.SuiteTest001_Login">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.f.dianqingoa.testcase.SuiteTest001_Login@c81cdd1]" name="beforeClass" is-config="true" duration-ms="12854" started-at="2019-07-12T05:30:05Z" finished-at="2019-07-12T05:30:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="testLogin(java.lang.String, java.lang.String)[pri:0, instance:com.f.dianqingoa.testcase.SuiteTest001_Login@c81cdd1]" name="testLogin" duration-ms="7453" started-at="2019-07-12T05:30:18Z" finished-at="2019-07-12T05:30:25Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[1357863545@qq.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[0108152535]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:com.f.dianqingoa.testcase.SuiteTest001_Login@c81cdd1]" name="afterClass" is-config="true" duration-ms="2230" started-at="2019-07-12T05:30:25Z" finished-at="2019-07-12T05:30:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- com.f.dianqingoa.testcase.SuiteTest001_Login -->
      <class name="com.f.dianqingoa.testcase.SuiteTest003_SwitchTitle">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.f.dianqingoa.testcase.SuiteTest003_SwitchTitle@75881071]" name="beforeClass" is-config="true" duration-ms="36086" started-at="2019-07-12T05:30:58Z" finished-at="2019-07-12T05:31:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="test01_switchCourse()[pri:0, instance:com.f.dianqingoa.testcase.SuiteTest003_SwitchTitle@75881071]" name="test01_switchCourse" duration-ms="2927" started-at="2019-07-12T05:31:34Z" finished-at="2019-07-12T05:31:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test01_switchCourse -->
        <test-method status="PASS" signature="test02_switchPracticalCourse()[pri:0, instance:com.f.dianqingoa.testcase.SuiteTest003_SwitchTitle@75881071]" name="test02_switchPracticalCourse" duration-ms="10351" started-at="2019-07-12T05:31:37Z" finished-at="2019-07-12T05:31:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test02_switchPracticalCourse -->
        <test-method status="PASS" signature="test03_switchEmploymentClasses()[pri:0, instance:com.f.dianqingoa.testcase.SuiteTest003_SwitchTitle@75881071]" name="test03_switchEmploymentClasses" duration-ms="13909" started-at="2019-07-12T05:31:48Z" finished-at="2019-07-12T05:32:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test03_switchEmploymentClasses -->
        <test-method status="PASS" signature="test04_switchSpecialColumn()[pri:0, instance:com.f.dianqingoa.testcase.SuiteTest003_SwitchTitle@75881071]" name="test04_switchSpecialColumn" duration-ms="8158" started-at="2019-07-12T05:32:01Z" finished-at="2019-07-12T05:32:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test04_switchSpecialColumn -->
        <test-method status="SKIP" signature="test05_switchApeAsk()[pri:0, instance:com.f.dianqingoa.testcase.SuiteTest003_SwitchTitle@75881071]" name="test05_switchApeAsk" duration-ms="3689" started-at="2019-07-12T05:32:10Z" finished-at="2019-07-12T05:32:13Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[跳转转失败！！！ expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 跳转转失败！！！ expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.f.dianqingoa.testcase.SuiteTest003_SwitchTitle.test05_switchApeAsk(SuiteTest003_SwitchTitle.java:113)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[RunCount=1]]>
            </line>
          </reporter-output>
        </test-method> <!-- test05_switchApeAsk -->
        <test-method status="SKIP" signature="test05_switchApeAsk()[pri:0, instance:com.f.dianqingoa.testcase.SuiteTest003_SwitchTitle@75881071]" name="test05_switchApeAsk" duration-ms="1624" started-at="2019-07-12T05:32:13Z" finished-at="2019-07-12T05:32:15Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[跳转转失败！！！ expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 跳转转失败！！！ expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.f.dianqingoa.testcase.SuiteTest003_SwitchTitle.test05_switchApeAsk(SuiteTest003_SwitchTitle.java:113)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.retryFailed(Invoker.java:838)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1009)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[RunCount=2]]>
            </line>
          </reporter-output>
        </test-method> <!-- test05_switchApeAsk -->
        <test-method status="SKIP" signature="test05_switchApeAsk()[pri:0, instance:com.f.dianqingoa.testcase.SuiteTest003_SwitchTitle@75881071]" name="test05_switchApeAsk" duration-ms="1548" started-at="2019-07-12T05:32:15Z" finished-at="2019-07-12T05:32:17Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[跳转转失败！！！ expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 跳转转失败！！！ expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.f.dianqingoa.testcase.SuiteTest003_SwitchTitle.test05_switchApeAsk(SuiteTest003_SwitchTitle.java:113)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.retryFailed(Invoker.java:838)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1009)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[RunCount=3]]>
            </line>
          </reporter-output>
        </test-method> <!-- test05_switchApeAsk -->
        <test-method status="SKIP" signature="test06_switchNotes()[pri:0, instance:com.f.dianqingoa.testcase.SuiteTest003_SwitchTitle@75881071]" name="test06_switchNotes" duration-ms="4345" started-at="2019-07-12T05:32:20Z" finished-at="2019-07-12T05:32:25Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[跳转转失败！！！ expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 跳转转失败！！！ expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.f.dianqingoa.testcase.SuiteTest003_SwitchTitle.test06_switchNotes(SuiteTest003_SwitchTitle.java:122)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[RunCount=1]]>
            </line>
          </reporter-output>
        </test-method> <!-- test06_switchNotes -->
        <test-method status="SKIP" signature="test06_switchNotes()[pri:0, instance:com.f.dianqingoa.testcase.SuiteTest003_SwitchTitle@75881071]" name="test06_switchNotes" duration-ms="3698" started-at="2019-07-12T05:32:25Z" finished-at="2019-07-12T05:32:28Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[跳转转失败！！！ expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 跳转转失败！！！ expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.f.dianqingoa.testcase.SuiteTest003_SwitchTitle.test06_switchNotes(SuiteTest003_SwitchTitle.java:122)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.retryFailed(Invoker.java:838)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1009)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[RunCount=2]]>
            </line>
          </reporter-output>
        </test-method> <!-- test06_switchNotes -->
        <test-method status="SKIP" signature="test06_switchNotes()[pri:0, instance:com.f.dianqingoa.testcase.SuiteTest003_SwitchTitle@75881071]" name="test06_switchNotes" duration-ms="3760" started-at="2019-07-12T05:32:28Z" finished-at="2019-07-12T05:32:32Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[跳转转失败！！！ expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 跳转转失败！！！ expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.f.dianqingoa.testcase.SuiteTest003_SwitchTitle.test06_switchNotes(SuiteTest003_SwitchTitle.java:122)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.retryFailed(Invoker.java:838)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1009)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[RunCount=3]]>
            </line>
          </reporter-output>
        </test-method> <!-- test06_switchNotes -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:com.f.dianqingoa.testcase.SuiteTest003_SwitchTitle@75881071]" name="afterClass" is-config="true" duration-ms="3363" started-at="2019-07-12T05:32:36Z" finished-at="2019-07-12T05:32:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- com.f.dianqingoa.testcase.SuiteTest003_SwitchTitle -->
    </test> <!-- Test2 -->
  </suite> <!-- Suite -->
</testng-results>
